version: "3.8"

services:
  server:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=your_jwt_secret
    volumes:
      - ./server:/app
    depends_on:
      - mongo
    networks:
      - app-network

  client:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - app-network

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
